### PR TITLE
First iteration of an untested function that finds polymorphisms.

### PR DESCRIPTION
**Pull request by pharos916**
Will need to add tests later.

### CODE REVIEW

**Comment by ericmjl** [comment]
I have added an automated test coverage report. If you look at the Travis CI output, look for something that says "-----coverage...-----". The lines of code in each of the files that have not been tested are listed there. Let me know if you've got questions!

**Comment by ericmjl** [comment]
Mostly pep8 fixes required. Also the latest lines need tests :).

**Comment by ericmjl** [comment]
Ok, I have inspected the changes and they look good. Merging.

**Comment by pharos916** [comment]
Since I still need to implement the test for this function, shouldn't we still have this branch active?

**Comment by ericmjl** [comment]
That was my bad. Go ahead and resurrect it!

**Pull request merged**
